In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import collections
import csv
import time

In [2]:
import numpy as py
import pandas as pd

In [3]:
driver = webdriver.Chrome("/Users/zhengyi/Documents/Analytics Tool/Codes/chromedriver")

In [87]:
"""teams = ["BOS","TOR","NYK","PHI","NJN","WAS","ATL","MIA","CHH","ORL","CLE","MIL","IND","CHI","DET",
        "UTA","SEA","POR","DEN","MIN","SAS","HOU","VAN","NOH","DAL","GSW","LAC","SAC","LAL","PHO"]"""
teams = ["BOS","TOR","NYK","PHI","NJN","WAS","ATL","MIA","CHH","ORL","CLE","MIL","IND","CHI","DET",
        "UTA","SEA","POR","DEN","MIN","SAS","HOU","VAN","DAL","GSW","LAC","SAC","LAL","PHO"]

In [4]:
def getPlayerSalaryV1(teams,years):
    salary_list = list()
    error_list = list()
    for year in years:
        for team in teams:
            url = "http://www.basketball-reference.com/teams/%s/%d.html" % (team, year)
            driver.get(url)
            try:
                salary = driver.find_element_by_id("salaries2").text
                salaries = salary.split("\n")[1:]
                for player in salaries:
                    temp = player.split(" ")
                    name = " ".join(temp[1:-1])
                    num = ''.join(temp[-1][1:].split(","))
                    salary_list.append((team,int(year),name,int(num)))
            except:
                error_list.append((year,team))
    return salary_list,error_list

In [5]:
def getPlayerSalaryV2(teams,years):
    salary_list = list()
    error_list = list()
    for year in years:
        for team in teams:
            url = "http://www.basketball-reference.com/teams/%s/%d.html" % (team, year)
            driver.get(url)
            try:
                salary = driver.find_element_by_id("all_salaries").text
                salaries = salary.split("\n")[2:]
                for player in salaries:
                    temp = player.split(" ")
                    name = " ".join(temp[1:-1])
                    num = ''.join(temp[-1][1:].split(","))
                    salary_list.append((team,int(year),name,int(num)))
            except:
                error_list.append((year,team))
    return salary_list,error_list

In [60]:
def getPlayerSalaryV3(teams,years):
    salary_list = list()
    error_list = list()
    for year in years:
        for team in teams:
            url = "http://www.basketball-reference.com/teams/%s/%d.html" % (team, year)
            driver.get(url)
            try:
                salary = driver.find_element_by_id("all_salaries2").text
                salaries = salary.split("\n")[2:]
                for player in salaries:
                    temp = player.split(" ")
                    name = " ".join(temp[1:-1])
                    num = ''.join(temp[-1][1:].split(","))
                    salary_list.append((team,int(year),name,int(num)))
            except:
                error_list.append((year,team))
    return salary_list,error_list

In [ ]:
#(NJN 2012 BRK 2013)
#(NOH 2003-2005 NOK 2006-2007 NOH 2008-2013 NOP 2014)
#(SEA 2008 OKC 2009)
#(CHH 2002 CHA 2005-2014 CHO 2015)
#VAN 2001 MEM 2002

In [89]:
salary_1996_2001,error_1996_2001 = getPlayerSalaryV2(teams,list(range(1996,2002)))

In [90]:
error_1996_2001

[(1996, 'WAS'), (1997, 'WAS')]

In [100]:
#url = "http://www.basketball-reference.com/teams/WSB/1996.html"
#driver.get(url)
#salary = driver.find_element_by_id("all_salaries").text

In [101]:
#salary

'Salaries\nRk Player Salary\n1 Chris Webber $7,000,000\n2 Mark Price $3,687,000\n3 Calbert Cheaney $2,800,000\n4 Gheorghe Muresan $1,963,000\n5 Juwan Howard $1,702,000\n6 Rasheed Wallace $1,493,000\n7 Robert Pack $1,304,000\n8 Jim McIlvaine $525,000\n9 Mitchell Butler $500,000\n10 Bob McCann $300,000\n11 Tim Legler $250,000\n12 Brent Price $250,000'

In [102]:
"""temp_list = list()
salaries = salary.split("\n")[2:]
for player in salaries:
    temp = player.split(" ")
    name = " ".join(temp[1:-1])
    num = ''.join(temp[-1][1:].split(","))
    salary_1996_2001.append(("WSB",int(1996),name,int(num)))"""

In [10]:
labels = ["Team","Year","Player","Salary"]

In [103]:
df = pd.DataFrame.from_records(salary_1996_2001,columns=labels)

In [104]:
print(len(df))
for team in df.Team.unique():
    total_contracts = len(df.loc[df["Team"] == team])
    print((team,total_contracts))

2696
('BOS', 100)
('TOR', 94)
('NYK', 92)
('PHI', 90)
('NJN', 96)
('ATL', 87)
('MIA', 103)
('CHH', 86)
('ORL', 111)
('CLE', 93)
('MIL', 85)
('IND', 102)
('CHI', 100)
('DET', 94)
('UTA', 83)
('SEA', 90)
('POR', 90)
('DEN', 90)
('MIN', 91)
('SAS', 87)
('HOU', 86)
('VAN', 93)
('DAL', 101)
('GSW', 95)
('LAC', 90)
('SAC', 91)
('LAL', 91)
('PHO', 96)
('WAS', 63)
('WSB', 26)

In [105]:
df.to_csv("NBA_Salary_1996_2001.csv")

In [2]:
NBA_Salary_2016_2017 = pd.DataFrame.from_csv("NBA_Salary_2016_2017.csv")

In [3]:
NBA_Salary_2015 = pd.DataFrame.from_csv("NBA_Salary_2015.csv")

In [4]:
NBA_Salary_2014 = pd.DataFrame.from_csv("NBA_Salary_2014.csv")

In [5]:
NBA_Salary_2013 = pd.DataFrame.from_csv("NBA_Salary_2013.csv")

In [6]:
NBA_Salary_2009_2012 = pd.DataFrame.from_csv("NBA_Salary_2009_2012.csv")

In [7]:
NBA_Salary_2008 = pd.DataFrame.from_csv("NBA_Salary_2008.csv")

In [8]:
NBA_Salary_2007 = pd.DataFrame.from_csv("NBA_Salary_2007.csv")

In [9]:
NBA_Salary_2006 = pd.DataFrame.from_csv("NBA_Salary_2006.csv")

In [10]:
NBA_Salary_2005 = pd.DataFrame.from_csv("NBA_Salary_2005.csv")

In [11]:
NBA_Salary_2003_2004 = pd.DataFrame.from_csv("NBA_Salary_2003_2004.csv")

In [12]:
NBA_Salary_2002 = pd.DataFrame.from_csv("NBA_Salary_2002.csv")

In [13]:
NBA_Salary_1996_2001 = pd.DataFrame.from_csv("NBA_Salary_1996_2001.csv")

In [25]:
NBA_Salary_2016_2017

     Team  Year             Player    Salary
0     BOS  2016          David Lee  15493680
1     BOS  2016       Amir Johnson  12000000
2     BOS  2016      Avery Bradley   7730337
3     BOS  2016      Isaiah Thomas   6912869
4     BOS  2016        Jae Crowder   6000000
5     BOS  2016      Jonas Jerebko   5000000
6     BOS  2016       Marcus Smart   3431040
7     BOS  2016        Evan Turner   3425510
8     BOS  2016       Tyler Zeller   2616975
9     BOS  2016    Jared Sullinger   2269260
10    BOS  2016       Kelly Olynyk   2165160
11    BOS  2016       Zoran Dragic   2050397
12    BOS  2016        Perry Jones   2038206
13    BOS  2016       Terry Rozier   1824360
14    BOS  2016        James Young   1749840
15    BOS  2016      Jordan Mickey   1200000
16    BOS  2016        R.J. Hunter   1148640
17    BOS  2016        Coty Clarke     61776
18    BOS  2016       Corey Walden     25000
19    BOS  2016     Malcolm Miller     25000
20    BOS  2016      Levi Randolph     25000
21    BOS  2016       John Holland      9266
22    TOR  2016    DeMarre Carroll  13500000
23    TOR  2016         Kyle Lowry  12000000
24    TOR  2016      DeMar DeRozan   9500000
25    TOR  2016        Cory Joseph   7000000
26    TOR  2016  Patrick Patterson   6268675
27    TOR  2016  Jonas Valanciunas   4660482
28    TOR  2016      Terrence Ross   3553917
29    TOR  2016    Bismack Biyombo   3000000
...   ...   ...                ...       ...
1177  LAL  2017    Thomas Robinson   1050961
1178  LAL  2017        Ivica Zubac   1034956
1179  LAL  2017      Anthony Brown    874636
1180  LAL  2017        Yi Jianlian    250000
1181  LAL  2017        David Nwaba     73528
1182  LAL  2017        David Nwaba     63938
1183  LAL  2017       Zach Auguste     60000
1184  PHO  2017       Eric Bledsoe  14000000
1185  PHO  2017     Brandon Knight  12606250
1186  PHO  2017     Tyson Chandler  12415000
1187  PHO  2017       Jared Dudley  10470000
1188  PHO  2017    Jared Sullinger   5628000
1189  PHO  2017           Alex Len   4823621
1190  PHO  2017      Dragan Bender   4276320
1191  PHO  2017    Leandro Barbosa   4000000
1192  PHO  2017         Mike Scott   3333334
1193  PHO  2017    Marquese Chriss   2941440
1194  PHO  2017       Devin Booker   2223600
1195  PHO  2017        T.J. Warren   2128920
1196  PHO  2017     Archie Goodwin   2094089
1197  PHO  2017         Tyler Ulis    918369
1198  PHO  2017      Alan Williams    874636
1199  PHO  2017    Michael Beasley    777777
1200  PHO  2017      Derrick Jones    543471
1201  PHO  2017       John Jenkins    469841
1202  PHO  2017       Ronnie Price    282595
1203  PHO  2017       Ronnie Price    182548
1204  PHO  2017       Jarell Eddie    102898
1205  PHO  2017     Elijah Millsap     23069
1206  PHO  2017     Elijah Millsap     23069

[1207 rows x 4 columns]

In [26]:
frames = [NBA_Salary_1996_2001,NBA_Salary_2002,NBA_Salary_2003_2004,NBA_Salary_2005,NBA_Salary_2006,NBA_Salary_2007,
         NBA_Salary_2008,NBA_Salary_2009_2012,NBA_Salary_2013,NBA_Salary_2014,NBA_Salary_2015,NBA_Salary_2016_2017]

In [27]:
NBA_Salary_96to17 = pd.concat(frames)

In [28]:
NBA_Salary_96to17

     Team  Year             Player    Salary
0     BOS  1996        Dana Barros   3300000
1     BOS  1996          Dee Brown   3000000
2     BOS  1996         Dino Radja   2640000
3     BOS  1996           Todd Day   2518000
4     BOS  1996           Rick Fox   1750000
5     BOS  1996     Pervis Ellison   1430000
6     BOS  1996      Eric Montross   1040000
7     BOS  1996      Eric Williams    876000
8     BOS  1996         Doug Smith    450000
9     BOS  1996         Greg Minor    325000
10    BOS  1996    Junior Burrough    300000
11    BOS  1996       Alton Lister    300000
12    BOS  1996       David Wesley    300000
13    TOR  1996        John Salley   2402000
14    TOR  1996      Oliver Miller   2372000
15    TOR  1996    Willie Anderson   2075000
16    TOR  1996        Ed Pinckney   1926000
17    TOR  1996   Victor Alexander   1595000
18    TOR  1996   Damon Stoudamire   1345000
19    TOR  1996          Acie Earl   1040000
20    TOR  1996      Carlos Rogers    930000
21    TOR  1996         B.J. Tyler    845000
22    TOR  1996          Zan Tabak    650000
23    TOR  1996    Tony Massenburg    550000
24    TOR  1996  Vincenzo Esposito    500000
25    TOR  1996         Jimmy King    300000
26    TOR  1996       Tracy Murray    250000
27    TOR  1996    Alvin Robertson    225000
28    TOR  1996       Martin Lewis    200000
29    NYK  1996      Patrick Ewing  18724000
...   ...   ...                ...       ...
1177  LAL  2017    Thomas Robinson   1050961
1178  LAL  2017        Ivica Zubac   1034956
1179  LAL  2017      Anthony Brown    874636
1180  LAL  2017        Yi Jianlian    250000
1181  LAL  2017        David Nwaba     73528
1182  LAL  2017        David Nwaba     63938
1183  LAL  2017       Zach Auguste     60000
1184  PHO  2017       Eric Bledsoe  14000000
1185  PHO  2017     Brandon Knight  12606250
1186  PHO  2017     Tyson Chandler  12415000
1187  PHO  2017       Jared Dudley  10470000
1188  PHO  2017    Jared Sullinger   5628000
1189  PHO  2017           Alex Len   4823621
1190  PHO  2017      Dragan Bender   4276320
1191  PHO  2017    Leandro Barbosa   4000000
1192  PHO  2017         Mike Scott   3333334
1193  PHO  2017    Marquese Chriss   2941440
1194  PHO  2017       Devin Booker   2223600
1195  PHO  2017        T.J. Warren   2128920
1196  PHO  2017     Archie Goodwin   2094089
1197  PHO  2017         Tyler Ulis    918369
1198  PHO  2017      Alan Williams    874636
1199  PHO  2017    Michael Beasley    777777
1200  PHO  2017      Derrick Jones    543471
1201  PHO  2017       John Jenkins    469841
1202  PHO  2017       Ronnie Price    282595
1203  PHO  2017       Ronnie Price    182548
1204  PHO  2017       Jarell Eddie    102898
1205  PHO  2017     Elijah Millsap     23069
1206  PHO  2017     Elijah Millsap     23069

[10632 rows x 4 columns]

In [30]:
NBA_Salary_96to17.to_csv("NBA_Salary_96to17.csv",index= False)